### PR TITLE
Simplify boolcase-mode-fix and provide "boolcase" instead of "boolcase-mode"

### PR DESCRIPTION
**Pull request by Jehops**

### CODE REVIEW

**Comment by gopar** [comment]
Hey Thanks for the PR.

One thing I'd like to mentioned is that I'd rather pass `'sexp` than `'word`. If I have a variable called `on_true` it'll automatically convert it to `on_True`, using `'sexp` this doesn't happen. Although having variables like that would be weird, it's still something I'd like to avoid. Would you mind fixing that up? Thanks :)

If you don't want to spoil the git history, you can make a separate PR for the `'sexp` fix and the `provide` bit, otherwise if you know how to do rebasing then power to ya \o/

**Comment by Jehops** [comment]
I have made a change,  so that 'on_true' is not converted to 'on_True'.

**Comment by Jehops** [comment]
You may also want to update the README, so that it does not mention the ability to add words.  This will not work, because, currently, only words ending in 'e' are checked.  Alternatively, you could modify `boolcase-mode-check`, so that it is active when all word characters are entered by the user.

I think your example should read `(add-hook 'python-mode-hook '(lambda () (boolcase-mode 1)))`.

**Comment by gopar** [comment]
Ha true, I should change the README. Thanks for catching that :)

Question: is there a reason you preferred adding the extra lines of code instead of changing the function to `(thing-at-point 'sexp)`? To me that would of been a lot simpler and wouldn't need to write extra code

**Comment by Jehops** [comment]
I think each major mode defines a sexp, so there may be gotchyas using sexp.  I would assume they don't (as often?) redefine a word.  If we use `(thing-at-point 'sexp)` something like "true will be converted to "True, which I assume you don't want.  I now see you would also have to modify the syntax table for word characters to address that case as well.

The deeper I dig, I can think of other issues, so maybe it's best you don't accept this.

**Pull request closed without merging**
